# Generated by Django 4.2 on 2023-05-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Col',
            fields=[
                ('col_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('col_name', models.CharField(max_length=200)),
                ('col_code', models.CharField(max_length=20, null=True, unique=True)),
                ('col_alt', models.IntegerField(null=True)),
                ('col_lon', models.FloatField(null=True)),
                ('col_lat', models.FloatField(null=True)),
                ('col_type', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
