# Generated by Django 4.2 on 2023-05-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('act_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('act_begin_date', models.DateTimeField()),
                ('act_dist', models.FloatField(null=True)),
                ('act_den', models.IntegerField(null=True)),
                ('act_type', models.CharField(max_length=10, null=True)),
                ('act_time', models.IntegerField(null=True)),
                ('act_avg', models.IntegerField(null=True)),
                ('act_power', models.IntegerField(null=True)),
                ('act_status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Col_counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('col_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Col_perform',
            fields=[
                ('col_perf_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('col_id', models.IntegerField()),
                ('act_id', models.IntegerField()),
            ],
        ),
    ]
