# Generated by Django 4.2 on 2023-05-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0004_rename_act_begin_date_activity_act_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_counter',
            name='col_id',
        ),
        migrations.RemoveField(
            model_name='col_perform',
            name='col_id',
        ),
        migrations.AddField(
            model_name='col_counter',
            name='col_code',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='col_perform',
            name='col_code',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
