# Generated by Django 4.2 on 2023-05-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0006_rename_act_id_col_perform_strava_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_counter',
            name='id',
        ),
        migrations.AddField(
            model_name='col_counter',
            name='col_count_id',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
