# Generated by Django 4.2 on 2023-06-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0007_remove_col_counter_id_col_counter_col_count_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col_counter',
            name='col_count_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
