# Generated by Django 4.2 on 2023-06-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0009_strava_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strava_user',
            name='athlete_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='strava_user',
            name='expire_at',
            field=models.IntegerField(null=True),
        ),
    ]
