# Generated by Django 4.2 on 2023-06-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0012_apollo_alter_col_perform_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apollo',
        ),
    ]
