# Generated by Django 4.2 on 2023-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0013_delete_apollo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apollo',
            fields=[
                ('apollo_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('apollo_name', models.CharField(default='-', max_length=100)),
            ],
        ),
    ]
