# Generated by Django 4.2 on 2023-06-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0014_apollo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apollo',
        ),
    ]
