# Generated by Django 4.2 on 2023-07-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0015_delete_apollo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
                ('country_lat', models.FloatField(null=True)),
                ('country_lon', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=3)),
                ('region_lat', models.FloatField(null=True)),
                ('region_lon', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_var',
            fields=[
                ('strava_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('view_region_id', models.IntegerField(null=True)),
            ],
        ),
    ]
