# Generated by Django 4.2 on 2023-07-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0016_country_region_user_var'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_var',
            name='strava_user',
            field=models.CharField(default='-', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_var',
            name='strava_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
