# Generated by Django 4.2 on 2023-07-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0017_user_var_strava_user_alter_user_var_strava_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_code',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='strava_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='region',
            name='country_code',
            field=models.CharField(default='00', max_length=3, null=True),
        ),
    ]
