# Generated by Django 4.2 on 2023-07-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0018_region_region_code_alter_activity_strava_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='strava_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='country_code',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_code',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
