# Generated by Django 4.2 on 2023-09-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0019_alter_activity_strava_id_alter_region_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_dashboard',
            fields=[
                ('strava_user', models.CharField(default='-', max_length=100, primary_key=True, serialize=False)),
                ('strava_user_id', models.IntegerField(null=True)),
                ('col_count', models.IntegerField(null=True)),
                ('col2000_count', models.IntegerField(null=True)),
                ('year_km', models.IntegerField(null=True)),
            ],
        ),
    ]
