# Generated by Django 4.2 on 2023-09-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0020_user_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_dashboard',
            old_name='year_km',
            new_name='bike_year_km',
        ),
        migrations.AddField(
            model_name='user_dashboard',
            name='run_year_km',
            field=models.IntegerField(null=True),
        ),
    ]
