# Generated by Django 4.2 on 2023-10-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0021_rename_year_km_user_dashboard_bike_year_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perform',
            fields=[
                ('perform_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('strava_perf_id', models.IntegerField(null=True)),
                ('segment_id', models.IntegerField()),
                ('perf_date', models.DateTimeField()),
                ('perf_chrono', models.IntegerField()),
                ('perf_vam', models.IntegerField()),
                ('perf_fc', models.IntegerField()),
                ('perf_fcmax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('segment_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('strava_segment_id', models.IntegerField(null=True)),
                ('activity_type', models.CharField(default='-', max_length=20)),
                ('segment_name', models.CharField(default='-', max_length=100)),
                ('slope', models.FloatField(null=True)),
                ('lenght', models.FloatField(null=True)),
                ('ascent', models.FloatField(null=True)),
            ],
        ),
    ]
