# Generated by Django 4.2 on 2023-10-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0023_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
