# Generated by Django 4.2 on 2023-10-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0025_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
