# Generated by Django 4.2 on 2023-10-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0027_patrice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patrice',
        ),
    ]
