# Generated by Django 4.2 on 2023-10-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0028_delete_patrice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_var',
            name='view_region_id',
        ),
        migrations.AddField(
            model_name='user_var',
            name='view_country_code',
            field=models.CharField(default='FRA', max_length=20),
        ),
        migrations.AddField(
            model_name='user_var',
            name='view_region_code',
            field=models.CharField(default='06', max_length=20),
        ),
    ]
