# Generated by Django 4.2 on 2023-11-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0030_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='bike_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='top_alt_col',
            field=models.IntegerField(null=True),
        ),
    ]
