# Generated by Django 4.2 on 2023-11-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0031_month_bike_time_month_top_alt_col'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Month',
            new_name='Month_stat',
        ),
    ]
