# Generated by Django 4.2 on 2023-11-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0032_rename_month_month_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month_stat',
            name='id',
        ),
        migrations.AddField(
            model_name='month_stat',
            name='month_stat_id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
