# Generated by Django 4.2 on 2023-11-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0033_remove_month_stat_id_month_stat_month_stat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frederic',
            fields=[
                ('prenom', models.CharField(default='-', max_length=100, primary_key=True, serialize=False)),
                ('Nom', models.CharField(default='-', max_length=100)),
            ],
        ),
    ]
