# Generated by Django 4.2 on 2023-11-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0034_frederic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frederic',
        ),
    ]
