# Generated by Django 4.2 on 2023-11-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0035_delete_frederic'),
    ]

    operations = [
        migrations.AddField(
            model_name='strava_user',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strava_user',
            name='strava_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
