# Generated by Django 4.2 on 2023-11-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0036_strava_user_id_alter_strava_user_strava_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='user_id',
            new_name='strava_user_id',
        ),
    ]
