# Generated by Django 4.2 on 2023-11-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0037_rename_user_id_activity_strava_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='col_counter',
            old_name='user_id',
            new_name='strava_user_id',
        ),
    ]
