# Generated by Django 4.2 on 2023-11-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0038_rename_user_id_col_counter_strava_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_dashboard',
            name='strava_user',
        ),
        migrations.AddField(
            model_name='user_dashboard',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
