# Generated by Django 4.2 on 2023-11-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0041_remove_strava_user_athlete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perform',
            name='strava_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
