# Generated by Django 4.2 on 2023-11-18 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0044_col_counter_year_col_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_counter',
            name='year_col_count',
        ),
    ]
