# Generated by Django 4.2 on 2023-11-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0046_col_counter_year_col_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code_100cols',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
