# Generated by Django 4.2 on 2023-11-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0047_country_code_100cols'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_counter',
            name='last_passage_date',
            field=models.DateTimeField(null=True),
        ),
    ]
