# Generated by Django 4.2 on 2023-11-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0048_col_counter_last_passage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='col_counter',
            name='last_passage',
            field=models.IntegerField(null=True),
        ),
    ]
