# Generated by Django 4.2 on 2023-11-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0049_col_counter_last_passage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='col_counter',
            old_name='last_passage',
            new_name='last_act_id',
        ),
    ]
