# Generated by Django 4.2 on 2023-12-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0050_rename_last_passage_col_counter_last_act_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='month_stat',
            name='pascal',
            field=models.IntegerField(null=True),
        ),
    ]
