# Generated by Django 4.2 on 2023-12-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0051_month_stat_pascal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month_stat',
            name='pascal',
        ),
    ]
