# Generated by Django 4.2 on 2024-02-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0052_remove_month_stat_pascal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_info',
            fields=[
                ('act_info_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('act_id', models.IntegerField(null=True)),
                ('info_txt', models.CharField(default='--', max_length=100)),
            ],
        ),
    ]
