# Generated by Django 4.2 on 2024-02-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0053_activity_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_info',
            name='info_txt',
            field=models.TextField(),
        ),
    ]
