# Generated by Django 4.2 on 2024-02-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StravaMap', '0054_alter_activity_info_info_txt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_info',
            old_name='act_id',
            new_name='strava_id',
        ),
    ]
