version : '3'

services : 

  web : 

    build: .

    #command : python manage.py runserver 0.0.0.0:8080

    volumes: 
      - .:/myapp

    ports:
      - '8000:80'   

    entrypoint:  /myapp/entrypoint.sh



  